### ISSUE TITLE
how to use lbs_read_fn?

### ISSUE THREAD

**Issue by serzhiio** [tephrocactus/lbs-rs#2]
I see lbs_read_fn in docs, but cant understand how to use it?
```
// Attributes available to this derive:
    #[lbs]
    #[lbs_default]
    #[lbs_read_fn]
```
It would be nice to have ability to implement custom read/write functions for specific fields.

**Comment by tephrocactus** [comment]
@serzhiio , please see [usage example](https://github.com/tephrocactus/lbs-rs#usage).
